### ISSUE TITLE
Bug: Build failure after merging PR #3

### ISSUE THREAD

**Issue by gomescx** [gomescx/memory-map-mind-elixir#5]
The deployment is failing with a TypeScript error:
  src/App.tsx#L415 — Property 'env' does not exist on type 'ImportMeta'

This was introduced in PR #3. Please fix the TypeScript error in src/App.tsx 
so the build compiles successfully and deploys to GitHub Pages.
